version: '3.8'
services:
  db:
    image: postgres:16-alpine # Bản Alpine siêu nhẹ
    container_name: zero_waste_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: ZeroWasteDB
    ports:
      - "5432:5432" # Cổng mặc định của Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: